config {
    type: "operations",
    hasOutput: false,
}
js {
    const { helpers } = require("includes/core/helpers");
    const config = helpers.getConfig();
    
    const fieldnames_sql = helpers.getEventParamKeysArray( config, ref("events_2025*"), "event_params");
    // const base_tbl = self() ;

    // const fieldnames_sql = helpers.getEventParamKeysArray("`pd-strategy.analytics_207462216.events_2025*`", "item_params");
    //[dataform.projectConfig.vars.OUTPUT_PROJECT, dataform.projectConfig.vars.TRANSFORMATIONS_DATASET, ].join(".");
}
 
${fieldnames_sql}; --${config.CUSTOM_EVENT_PARAMS_TO_EXCLUDE}
